### ISSUE TITLE
npm module not found 

### ISSUE THREAD

**Issue by zkavtaskin** [nathsou/Darwin#3]
Dear Nathan,

First of all I would like to say that I really like your work on Github. Please do keep it up!

I am currently using your Darwin module in one of my projects, as I have started to run the project I kept getting the following error: npm module not found charles.darwin

After a bit of digging I have found the issue, in your package.json you are missing "main" property. 
Please find screenshot attached with a fix. 

<img width="504" alt="Screenshot 2020-05-25 at 22 35 41" src="https://user-images.githubusercontent.com/2659868/82844626-0f4cba80-9ed9-11ea-882c-ec4ccbf8bc73.png">

**Comment by patwhite** [comment]
@zkavtaskin this is a silly question, but do you know if there is a way to work around this?

**Comment by nathsou** [comment]
Hey @zkavtaskin and @patwhite!

Thanks for the issue and my apologies for the missed notification.
I have updated the package.json to include the main property.

Cheers :)
